N = int(input("Please enter the number of passenger cars are on the train: ")) #Taking Input for Passenger Cars as N
Cars = 1 # Variable used to update the passenger car number
Adults = 0 # Variable used to keep track of Adults
Children = 0 # Variable used to keep track of Children

for Train in range(1,(N + 1)): # Initializing For Loop, Loops Until LCV = N +1
     print("For Car", Cars) # Prints Car Number
     Cars += 1 # Updates car number for next loop
     Adults += int(input("Enter the number of adults in the car:")) # Takes input for adults on train and updates their total
     Children += int(input("Enter the number of children in the car:")) # Takes input for adults on train and updates their total

Passengers = Adults + Children # Adds Children and Adults to get total amount of passengers

RevChildren = 120.50 * Children # Calculates Revenue Generated from Children
RevAdults = 320.00 * Adults # Calculates Revenue Generated from Adults
RevTotal = RevAdults + RevChildren # Calculates Revenue Generated in Total

PerAdults = ((RevAdults / RevTotal) * 100) # Calculates Percentage of Revenue Generated by Adults
PerChildren = ((RevChildren / RevTotal)* 100) # Calculates Percentage of Revenue Generated by Children


print("The total number of passangers on the train is", Passengers) #prints total Passengers
print("The percentage of the revenue from adult tickets is", (round(PerAdults,2)),"%") #round and prints Adult revenue percentage
print("The percentage of the revenue from child tickets is", (round(PerChildren,2)),"%")#round and prints Children revenue percentage